name: sentrei
description: Official sentrei app
version: 4.79.0

environment:
  sdk: ">=2.3.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  auto_size_text: ^2.1.0
  cached_network_image: ^2.0.0
  common_utils: ^1.1.3
  cupertino_icons: ^0.1.2
  dio: ^3.0.9
  flare_loading: ^2.1.1
  flutter_auth_buttons: ^0.8.0
  flutter_slidable: ^0.5.4
  firebase_analytics: ^5.0.11
  firebase_auth: ^0.15.5+3
  firebase_core: ^0.4.0+9
  firebase_database: ^3.1.3
  firebase_crashlytics: ^0.1.3+3
  firebase_dynamic_links: ^0.5.0+11
  firebase_messaging: ^6.0.13
  firebase_performance: ^0.3.1+7
  firebase_storage: ^3.1.5
  intl: ^0.16.0
  google_sign_in: ^4.4.0
  gradient_widgets: ^0.5.1
  package_info: ^0.4.0+16
  provider: ^4.0.4
  liquid_swipe: ^1.4.2
  lottie: ^0.3.3
  nested: ^0.0.4
  rxdart: ^0.23.1
  random_string: ^2.0.1
  shared_preferences: ^0.5.6+3
  synchronized: ^2.2.0

dev_dependencies:
  flutter_driver:
    sdk: flutter
  flutter_test:
    sdk: flutter
  intl_translation: ^0.17.9
  mockito: ^4.1.1
  pedantic: ^1.8.0+1
  test: ^1.9.4

flutter:
  assets:
    - assets/images/
    - assets/lottie/
  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Light.ttf
        - asset: assets/fonts/Montserrat-Medium.ttf
        - asset: assets/fonts/Montserrat-Regular.ttf
  uses-material-design: true
